language: node_js
node_js:
  - "8"
  
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-js.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=16534"
  - npm install

script:
  - node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > junit_output.xml

after_script:
  - hiptest-publisher -c cucumber-js.conf --token=$SECRET_TOKEN --push=junit_output.xml --test-run-id=16534
  - |
      curl -X POST https://livingdoc-jira-app.scalingo.io/connect/rest/api/r0esults \
        -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqaXJhOmQ3YTM3ZmI0LTY2ZDQtNDM4OS05MjRkLWZjMTY3N2RlZDBjOSIsImNvbnRleHQiOnsicHJvamVjdF9pZCI6IjEyMzY0IiwicmVwb3NpdG9yeV9uYW1lIjoibGF1cmVudFB5L2hwcy1jdWN1bWJlci1qYXZhc2NyaXB0In19.30ah_Lq6YLbJgufsKjet8TRPy7eDUy-AvsFDSeZfUsM' \
        -H 'content-type: multipart/form-data' \
        -F results_file=@results.json
